# Generated by Django 4.0.5 on 2022-07-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_todo',
            name='id',
            field=models.IntegerField(primary_key=b'I01\n', serialize=False),
        ),
        migrations.AlterField(
            model_name='done_todo',
            name='id',
            field=models.IntegerField(primary_key=b'I01\n', serialize=False),
        ),
        migrations.AlterField(
            model_name='history_todo',
            name='id',
            field=models.IntegerField(primary_key=b'I01\n', serialize=False),
        ),
    ]
