# Generated by Django 4.0.5 on 2022-08-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_app', '0002_alter_all_todo_id_alter_done_todo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='done_todo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=111),
            preserve_default=False,
        ),
    ]
