# Generated by Django 4.0.5 on 2022-08-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='password',
            new_name='address',
        ),
    ]
